# Generated by Django 4.2 on 2025-02-03 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('last_day', models.DateField()),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('incomplete', '未完了'), ('complete', '完了')], default='incomplete', max_length=10)),
            ],
            options={
                'ordering': ['last_day'],
            },
        ),
    ]
